name: Build and Test
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        node: [ '10', '12', '14' ]
    name: Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm install -g npm@7
      - run: npm ci
      - run: npm run test
      - run: npm run coverage

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
